//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QD_Project1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ad_master
    {
        public decimal Tid { get; set; }
        public string Title { get; set; }
        public string Category { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Photos { get; set; }
        public string Tag { get; set; }
        public string AdType { get; set; }
        public string Sub_Category { get; set; }
        public string Ad_Condition { get; set; }
    }
}
