//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QD_Project1._0
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User_Master
    {
        public decimal Uid { get; set; }
        [Required ]
        public string UserName { get; set; }
        [Required]
        public string Password { get; set; }
        public string skey { get; set; }
        [RegularExpression(@"\A(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?)\Z", ErrorMessage = "Invalid Email Id")]
        public string Email { get; set; }
        [Required]
        [StringLength(10)]
        public string Contact { get; set; }
        [Required]
        public Nullable<decimal> Province { get; set; }
        [Required]
        public Nullable<decimal> City { get; set; }
        public string IsActive { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        [Required]
        [StringLength(7)]
        public string Postal_Code { get; set; }
    
        public virtual City_master City_master { get; set; }
        public virtual Province_Master Province_Master { get; set; }
        public virtual User_Master User_Master1 { get; set; }
        public virtual User_Master User_Master2 { get; set; }
    }
}
